version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '4200:80'

  backend:
    build: ./backend
    restart: always
    ports:
      - '8443:8443'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql_db/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data:
